### PR TITLE
Correct logging when mission is accepted

### PR DESCRIPTION
**Pull request by anetteu**
A mission that is recieved, accepted, and initiated by ISAR is not necessarily started by the robot.

### CODE REVIEW

**Comment by GodVenn** [comment]
But isn't it started in ISAR?

**Review by GodVenn — DISMISSED** [review]
I agree that it was confusing before, but "start" and "initiate" have the same meanings.
And I think the error message should say failed to start instead of accept, since with accept it may sound like the mission is in the wrong format or contains invalid information, which is not the case with QueueTimeouts.

**Comment by aestene** [comment]
This pull request has automatically been marked as stale as there has been no activity for 30 days.

**Review by aestene — APPROVED** [review]
LGTM

**Pull request merged**
