### PR TITLE
replace occurrences of 'name' with 'type'

### PR DESCRIPTION
**Pull request by PracticalMetal**
With reference to the issue #157, I've made the required changes in `src/robot_interface/models/mission/task.py` and the `json` files in `src/isar/config/predefined_missions/`. Do let me know what you think about it. Thanks

### CODE REVIEW

**Comment by aestene** [comment]
Thank you for the PR @PracticalMetal!

I see that the change from `name` to `type` has also affected the system to a larger extent than just these files. This is causing the tests to fail currently.

There are mainly two issues:
1. Test data files with missions which still have `name` instead of `type`. Have a look at the mission files in [this folder](https://github.com/equinor/isar/tree/main/tests/test_data).
2. The second part is related to a few places in the code where `task.name` is used explicitly and it should be changed to `task.type` instead.

https://github.com/equinor/isar/blob/ef64fb5db47e1a2a4b59b8bc8c91067245909299/src/isar/state_machine/states/cancel.py#L82
https://github.com/equinor/isar/blob/ef64fb5db47e1a2a4b59b8bc8c91067245909299/src/isar/state_machine/states/send.py#L65
https://github.com/equinor/isar/blob/ef64fb5db47e1a2a4b59b8bc8c91067245909299/tests/isar/services/readers/test_mission_reader.py#L80

I recommend looking at [this section](https://github.com/equinor/isar#running-tests) of the readme for running tests locally. Please reach out to us if there are any issues with running the tests.

**Review by aestene — CHANGES_REQUESTED** [review]
Have a look at my previous comment. In addition, we try to follow [this set of rules](https://cbea.ms/git-commit/) for writing git commit messages so you should capitalize the commit message.

**Comment by PracticalMetal** [comment]
Thankyou for your response, will do the required changes

**Comment by PracticalMetal** [comment]
Hey I was trying to test the  code locally on my machine and whenever I try to `pip install -e .[dev]` and do `pytest .`, I am encountered with several errors like
```
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/WSL_Pulkit/Github/isar/setup.py'"'"'; __file__='"'"'/mnt/c/WSL_Pulkit/Github/isar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
```
I've tried searching the web for the solution but couldn't find any. I am using Ubuntu on my local machine. I would be great if you could guide me on how I can fix this issue.

**Comment by aestene** [comment]
> Hey I was trying to test the code locally on my machine and whenever I try to `pip install -e .[dev]` and do `pytest .`, I am encountered with several errors like
> 
> ```
>  ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/WSL_Pulkit/Github/isar/setup.py'"'"'; __file__='"'"'/mnt/c/WSL_Pulkit/Github/isar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
> ```
> 
> I've tried searching the web for the solution but couldn't find any. I am using Ubuntu on my local machine. I would be great if you could guide me on how I can fix this issue.

Mhm, it's not an error I have seen before and I suspect it's related to your local setup more than it's related to ISAR and the pip installation itself. Do you have more error logs to provide?

In any case, you can push your changes to your fork and we can verify if the tests run in the pipeline. Not an ideal and efficient solution but if you're not able to resolve the local errors it can be a workaround.

**Comment by aestene** [comment]
Hi @PracticalMetal!

Would you like to address the remainder of the review? Otherwise I will close this PR.

**Comment by aestene** [comment]
Closing due to inactivity.

**Pull request closed without merging**
