### PR TITLE
Remove all implementation of joints

### PR DESCRIPTION
**Pull request by tsundvoll**
This is instead handled in the robot specific code and this PR will have therefore have a corresponding PR in the robot specific repo. Wait for that before merging this.

### CODE REVIEW

**Comment by tsundvoll** [comment]
This PR will have a corresponding PR in the robot specific repo

**Review by vetlek — APPROVED** [review]
LGTM

**Review by Christdej — APPROVED** [review]
LGTM

**Review by aestene — APPROVED** [review]
LGTM

**Pull request merged**
