### PR TITLE
Remove unused method in `StartMissionMessages`

### LINKED ISSUE #140: Can `invalid_mission_id(mission_id: int) -> StartMessage` be removed?
**Describe the improvement you would like to see**
This method does not seem to be in use in ISAR. If it is not in use in other ISAR related repositories, it should be removed.

**How will this change existing functionality?**
Should not change any functionality, just cleanup unused code. 

**How will this improvement affect the current Threat Model?**
Should not affect Threat Model.

### PR DESCRIPTION
**Pull request by autt**
Close #140

### CODE REVIEW

**Review by tsundvoll — CHANGES_REQUESTED** [review]
Good. I see that several other of the methods in this file is not in use. Could we remove them in the same commit?

**Comment by autt** [comment]
Good catch @tsundvoll. The ones you listed are now removed, together with a last method that were only used in tests.

**Review by vetlek — APPROVED** [review]
LGTM

**Review by tsundvoll — APPROVED** [review]
Very good :+1:

**Pull request merged**
